ALTER TABLE `cliente` ADD COLUMN `cnpj` CHAR(18) DEFAULT NULL;
ALTER TABLE `cliente` ADD COLUMN `cpf` CHAR(14) DEFAULT NULL;
ALTER TABLE `cliente` ADD COLUMN `fone1` CHAR(15) DEFAULT NULL;
ALTER TABLE `cliente` ADD COLUMN `fone2` CHAR(15) DEFAULT NULL;
ALTER TABLE `cliente` ADD COLUMN `email` VARCHAR(100) DEFAULT NULL;